nodeLinker: node-modules
packageExtensions:
  "@volontariapp/errors-nest@*":
    peerDependenciesMeta:
      "@nestjs/common":
        optional: true
      "@nestjs/core":
        optional: true
      "@nestjs/microservices":
        optional: true
      "@nestjs/swagger":
        optional: true
  "@nestjs/common@*":
    peerDependenciesMeta:
      rxjs:
        optional: true
      reflect-metadata:
        optional: true
  terser-webpack-plugin@*:
    peerDependenciesMeta:
      "@types/esbuild":
        optional: true
      esbuild:
        optional: true
      uglify-js:
        optional: true
      swc:
        optional: true
  "@nestjs/core@*":
    peerDependenciesMeta:
      rxjs:
        optional: true
      reflect-metadata:
        optional: true
