name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  ci:
    uses: Volontariapp/ci-tools/.github/workflows/service-ci.yml@main
    with:
      service-name: ws-service
    secrets: inherit

  ci-docker:
    needs: ci
    permissions:
      contents: read
      packages: write
    uses: Volontariapp/ci-tools/.github/workflows/service-docker-build-push.yml@main
    with:
      service-name: ws-service
    secrets: inherit
