name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  ci:
    uses: Volontariapp/ci-tools/.github/workflows/service-ci.yml@main
    with:
      service-name: ws-service
    secrets: inherit
